services:
- type: web
  name: nse-scraper
  runtime: docker
  repo: https://github.com/jagdishuipath/nse-scraper
  plan: free
  region: oregon
  envVars:
    - key: NODE_ENV
      value: production
    - key: NODE_OPTIONS
      value: "--max-old-space-size=512"
  autoDeployTrigger: commit
